{
 "title": "Basic Resources",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "metric.label.instance_name" ],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "{{PROJECT_NAME}}",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Network Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "metric.label.instance_name" ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "{{PROJECT_NAME}}",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Network Received Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "metric.label.instance_name" ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "{{PROJECT_NAME}}",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "metric.label.instance_name" ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/read_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "{{PROJECT_NAME}}",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk Write Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [],
      "groupBys": [ "metric.label.instance_name" ],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/write_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "{{PROJECT_NAME}}",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}